---
- name: Проверка доступности хостов
  hosts: upravlenie, podrazdeleniya
  become: yes
  gather_facts: false

  tasks:
  - name: Проверка наличие соединения с хостами
    ping:

  - name: Вывод сведений о хостах
    debug:
      msg:
      - Подразделение - {{ unit }}
      - Телефон - {{ phone }}
      - ip-адрес - {{ ansible_host }}
      - Пользователь - {{ owner }}
...